import { z } from "zod";
declare const envSchema: z.ZodObject<{
    GITHUB_TOKEN: z.ZodOptional<z.ZodString>;
    GITHUB_ORG_NAME: z.ZodDefault<z.ZodString>;
    PUBLIC_SITE_DOMAIN: z.ZodDefault<z.ZodString>;
    PROJECT_SITE_TEMPLATE: z.ZodDefault<z.ZodString>;
    DEFAULT_LICENSE: z.ZodDefault<z.ZodString>;
    MIN_RUN_USD: z.ZodEffects<z.ZodOptional<z.ZodString>, number, string | undefined>;
    MAX_RUN_USD: z.ZodEffects<z.ZodOptional<z.ZodString>, number, string | undefined>;
    GLOBAL_MAX_CONCURRENT_RUNS: z.ZodEffects<z.ZodOptional<z.ZodString>, number, string | undefined>;
    GLOBAL_MAX_DAILY_SPEND_USD: z.ZodEffects<z.ZodOptional<z.ZodString>, number, string | undefined>;
    PER_PROJECT_MAX_DAILY_SPEND_USD: z.ZodEffects<z.ZodOptional<z.ZodString>, number, string | undefined>;
    LLM_PROVIDER_DEFAULT: z.ZodDefault<z.ZodString>;
    LLM_MODEL_DEFAULT: z.ZodDefault<z.ZodString>;
    AGENT_RUNTIME_DEFAULT: z.ZodDefault<z.ZodString>;
    BACKEND_BASE_URL: z.ZodOptional<z.ZodString>;
    RUN_TOKEN_TTL_MINUTES: z.ZodEffects<z.ZodOptional<z.ZodString>, number, string | undefined>;
    RUN_QUEUE_CHECK_LIMIT: z.ZodEffects<z.ZodOptional<z.ZodString>, number, string | undefined>;
    BUCKET_RUNTIME_MINUTES_PER_USD: z.ZodEffects<z.ZodOptional<z.ZodString>, number, string | undefined>;
    BUCKET_TOKENS_PER_USD: z.ZodEffects<z.ZodOptional<z.ZodString>, number, string | undefined>;
}, "strip", z.ZodTypeAny, {
    GITHUB_ORG_NAME: string;
    PUBLIC_SITE_DOMAIN: string;
    PROJECT_SITE_TEMPLATE: string;
    DEFAULT_LICENSE: string;
    MIN_RUN_USD: number;
    MAX_RUN_USD: number;
    GLOBAL_MAX_CONCURRENT_RUNS: number;
    GLOBAL_MAX_DAILY_SPEND_USD: number;
    PER_PROJECT_MAX_DAILY_SPEND_USD: number;
    LLM_PROVIDER_DEFAULT: string;
    LLM_MODEL_DEFAULT: string;
    AGENT_RUNTIME_DEFAULT: string;
    RUN_TOKEN_TTL_MINUTES: number;
    RUN_QUEUE_CHECK_LIMIT: number;
    BUCKET_RUNTIME_MINUTES_PER_USD: number;
    BUCKET_TOKENS_PER_USD: number;
    GITHUB_TOKEN?: string | undefined;
    BACKEND_BASE_URL?: string | undefined;
}, {
    GITHUB_TOKEN?: string | undefined;
    GITHUB_ORG_NAME?: string | undefined;
    PUBLIC_SITE_DOMAIN?: string | undefined;
    PROJECT_SITE_TEMPLATE?: string | undefined;
    DEFAULT_LICENSE?: string | undefined;
    MIN_RUN_USD?: string | undefined;
    MAX_RUN_USD?: string | undefined;
    GLOBAL_MAX_CONCURRENT_RUNS?: string | undefined;
    GLOBAL_MAX_DAILY_SPEND_USD?: string | undefined;
    PER_PROJECT_MAX_DAILY_SPEND_USD?: string | undefined;
    LLM_PROVIDER_DEFAULT?: string | undefined;
    LLM_MODEL_DEFAULT?: string | undefined;
    AGENT_RUNTIME_DEFAULT?: string | undefined;
    BACKEND_BASE_URL?: string | undefined;
    RUN_TOKEN_TTL_MINUTES?: string | undefined;
    RUN_QUEUE_CHECK_LIMIT?: string | undefined;
    BUCKET_RUNTIME_MINUTES_PER_USD?: string | undefined;
    BUCKET_TOKENS_PER_USD?: string | undefined;
}>;
export type EnvConfig = z.infer<typeof envSchema> & {
    minRunCents: number;
    maxRunCents: number;
    globalMaxDailySpendCents: number;
    perProjectMaxDailySpendCents: number;
};
export declare function getEnvConfig(): EnvConfig;
export declare function usdToCents(amountUsd: number): number;
export {};
